version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: factcheck-app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
